[package]
name = "nelius-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
futures = "0.3.31"
iced = "0.14.0"
reqwest = { version = "0.13.2", features = ["json"]}
rfd = "0.17.2"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
